config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => "homes#about", as: 'about'
  root to: "homes#top"
  devise_for :users

  resources :books, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :my_books
    end
  end
  resources :users, only: [:index, :show, :edit, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image  
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:name]

  before_validation { self.name = name.to_s.strip }

  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }, allow_blank: true

  has_many :books, dependent: :destroy
  has_many :post_images, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    if profile_image.attached?
      profile_image.variant(resize_to_limit: [width, height]).processed
    else
      'no_image.jpg'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :prepare_sidebar_book, if: :user_signed_in?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  private
  def prepare_sidebar_book
    return if controller_name == "homes" || %w(edit update).include?(action_name)
    @new_book = Book.new
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_new_book, only: [:index, :my_books, :show]
  before_action :set_book,     only: [:show]
  before_action :set_own_book, only: [:edit, :update, :destroy]
  

  def index
    @books = Book
      .includes(user: { profile_image_attachment: :blob })
      .order(created_at: :desc)
    @user = current_user
    @new_book = Book.new
  end
    
  def show; 
    @user = @book.user
    @new_book = Book.new
  end
  
  def edit; end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: "You have updated book successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, notice: "Book was deleted."
  end
  
  def create
    @new_book = current_user.books.build(book_params)
    if @new_book.save
      redirect_to @new_book, notice: "You have created book successfully."
    else
      @books = Book.includes(user: { profile_image_attachment: :blob }).order(created_at: :desc)
      @user =current_user
      flash.now[:errors] = @new_book.errors.full_messages
      render :index, status: :unprocessable_entity
    end
  end
  
  def my_books
    @books = current_user.books
              .includes(user: { profile_image_attachment: :blob })
              .order(created_at: :desc)
    render :index
  end

  private
  def set_new_book; @new_book = Book.new; end
  def set_book;     @book = Book.find(params[:id]); end
  def set_own_book
    @book = current_user.books.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to books_path, alert: "権限がありません。"
  end
  def book_params;  params.require(:book).permit(:title, :body); end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]
  before_action :ensure_current_user!, only: [:edit, :update]
  
  def show
    @books = @user.books
                  .includes(user: { profile_image_attachment: :blob })
                  .order(created_at: :desc)
  end

  def edit
  end

  def index
    @users = User.all
    @user = current_user
    @new_book = Book.new
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "You have updated user successfully."
    else
     render :edit, status: :unprocessable_entity
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def ensure_current_user!
    user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user), alert: "権限がありません。"
    end
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<!-- app/views/books/_form.html.erb -->

<h3>New book</h3>
<%= form_with model: book, url: books_path do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div>
    <%= f.label :body, "Opinion" %>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <%= f.submit "Create Book", class: "btn btn-success mt-3" %>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
    <ul class="mb-0">
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @book do |f| %>
  <div class="mb-3">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :body, "Opinion" %>
    <%= f.text_area :body, rows: 4, class: "form-control" %>
  </div>

  <%= f.submit "Update Book", class: "btn btn-success" %>
<% end %>

<p class="mt-2">
  <%= link_to "Show", book_path(@book) %> |
  <%= link_to "Back", books_path %>
</p>

app/views/books/index.html.erb
<!-- app/views/books/index.html.erb -->

<aside class="col-md-3 mb-4">
  <%= render "users/info", user: @user %>
  <%= render "books/form", book: @new_book %>
</aside>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
              <%= image_tag book.user.get_profile_image(60, 60), size: "60x60", alt: book.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book.title, book_path(book) %><br>
          </td>
          <td><%= simple_format(book.body) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/show.html.erb
<aside class="col-md-3 mb-4">
  <%= render "users/info", user: @user %>
  <%= render "books/form", book: @new_book %>
</aside>

<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <div class="book-detail">
    <div class="media">
      <%= link_to user_path(@book.user) do %>
        <%= image_tag @book.user.get_profile_image(120, 120), size: "120x120", alt: @book.user.name %>
      <% end %>
      <div class="media-body" style="margin-left: 16px;">
        <div>
          <%= link_to @book.title, book_path(@book) %>
        </div>
        <div>
          <%= simple_format(@book.body) %>
        </div>
        <div>
          <%= link_to @book.user.name, user_path(@book.user) %>
        </div>
      </div>
    </div>
  </div>

  <%# 自分の投稿だけ編集/削除ボタンを表示 %>
  <% if user_signed_in? && current_user == @book.user %>
  <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success btn-sm" %>
  <%= link_to "Destroy", book_path(@book),
              method: :delete,
              data: { confirm: "Are you sure?" },
              class: "btn btn-danger btn-sm" %>
  <% end %>
</div>

app/views/homes/about.html.erb
<h1>Welcome to <i class="fa-solid fa-book"></i>Bookers!</h1>

app/views/homes/top.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <!-- 見出しは左寄せ -->
      <h1 class="display-4 font-weight-bold mb-3">
        welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!
      </h1>

      <!-- 段落だけ左寄せ（Bootstrap4 は text-left） -->
      <p class="mb-1 text-left">
        In <i class="fas fa-book"></i><strong>Bookers</strong>,
      </p>
      <p class="mb-4 text-left">
        you can share and exchange your opinions , impressions , and emotions<br>
        about various books!
      </p>

      <!-- ボタンは中央寄せ -->
      <div class="text-center">
        <%= link_to "Log in",
                    new_user_session_path,
                    class: "btn btn-info btn-lg btn-block mx-auto mb-3",
                    style: "max-width: 480px;" %>

        <%= link_to "Sign up",
                    new_user_registration_path,
                    class: "btn btn-success btn-lg btn-block mx-auto",
                    style: "max-width: 480px;" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/ddeb48cbe9.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="mb-3">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
          <!-- 左：ブランド -->
          <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
            <span>Bookers</span>
          <% end %>

          <!-- 右：リンク群 -->
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user), class: "nav-link" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: "nav-link" do %>
                  <i class="fas fa-users"></i> Users
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: "nav-link" do %>
                  <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
                  <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: "nav-link" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to about_path, class: "nav-link" do %>
                  <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: "nav-link" do %>
                  <i class="fas fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: "nav-link" do %>
                  <i class="fas fa-sign-in-alt"></i> Log in
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <% flash.each do |key, message| %>
      <% next if key.to_s == "errors" %>  
      <div class="alert alert-<%= key == "notice" ? "success" : "danger" %>">
        <%= message %>
      </div>
    <% end %>
    
    <%# ★ 詳細エラーはここだけで表示（1か所だけ） %>
    <% if (errs = (flash.now[:errors] || flash[:errors])).present? %>
      <% errs = Array(errs) %>
      <div class="alert alert-danger">
        <h4><%= pluralize(errs.size, "error") %> prohibited this action:</h4>
        <ul class="mb-0">
          <% errs.each do |msg| %><li><%= msg %></li><% end %>
        </ul>
      </div>
    <% end %>

    <main>
      <div class="container">
        <div class ="row">            
          <%= yield %>
        </div>
      </div>
    </main>

    <footer class="text-center mt-5">
      <p>CopyRight infratop.inc</p>
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
<!-- ログイン中ユーザー情報（共通） -->
<div class="user-info mb-4">
    <h2 class="h2 mb-3">User info</h2>

    <div class="mb-3">
      <%= image_tag user.get_profile_image(120, 120), alt: "avatar", size: "120x120" %>
    </div>

    <table class="table table-sm">
      <tr><th>name</th><td><%= user.name %></td></tr>
      <% if user.respond_to?(:introduction) %>
        <tr><th>introduction</th><td><%= user.introduction %></td></tr>
      <% end %>
    </table>

    <%= link_to raw('<i class="fas fa-user-cog"></i>'),
            edit_user_path(user),
            class: "btn btn-outline-secondary btn-block" %>
</div>

app/views/users/edit.html.erb
<h1>User info</h1>

<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h2>
    <ul class="mb-0">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @user do |f| %>
  <div class="mb-3">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :profile_image, "Image" %>
    <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file" %>
  </div>

  <div class="mb-3">
    <%= f.label :introduction, "Introduction" %>
    <%= f.text_area :introduction, rows: 5, class: "form-control" %>
  </div>

  <%= f.submit "Update User", class: "btn btn-primary" %>
<% end %>

app/views/users/index.html.erb
<!-- app/views/users/index.html.erb -->
<aside class="col-md-3 mb-4">
  <%= render "users/info", user: @user %>
  <%= render "books/form", book: @new_book %>
</aside>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user_path(user) do %>
              <%= image_tag user.get_profile_image(60, 60), size: "60x60", alt: user.name %>
            <% end %>
          </td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<aside class="col-md-3 mb-4">
  <%= render "users/info", user: @user %>
  <%= render "books/form", book: @new_book %>
</aside>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
              <%= image_tag @user.get_profile_image(60, 60), size: "60x60", alt: @user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book.title, book_path(book) %>  <!-- book の show へ -->
          </td>
          <td><%= simple_format(book.body) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>